# Generated by Django 2.0.2 on 2018-02-25 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=16, null=True)),
                ('value', models.DecimalField(decimal_places=10, default=0.0, max_digits=20, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('prop', models.IntegerField(default=50, null=True)),
            ],
        ),
    ]
