# Generated by Django 2.0.2 on 2018-02-26 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование валюты', max_length=16, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(help_text='Наименование валюты', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='prop',
            field=models.IntegerField(blank=True, default=50, help_text='Доля участников, ставящих на повышение, %', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время'),
        ),
        migrations.AlterField(
            model_name='course',
            name='value',
            field=models.DecimalField(decimal_places=10, default=0.0, help_text='Значение', max_digits=20, null=True),
        ),
    ]
