# Generated by Django 2.0.2 on 2018-02-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_currencygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='group',
            field=models.CharField(help_text='Наименование', max_length=16, null=True),
        ),
    ]
