# Generated by Django 2.0.2 on 2018-02-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_currency_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(default=0, help_text='Наименование валюты', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='group',
            field=models.CharField(choices=[('Валюты', 'Валюты'), ('Биржевые акции', 'Биржевые акции'), ('Криптоактивы', 'Криптоактивы'), ('Индексы', 'Индексы'), ('Сырье', 'Сырье')], help_text='Наименование', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='Наименование валюты', max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currencygroup',
            name='name',
            field=models.CharField(help_text='Наименование', max_length=16, null=True, unique=True),
        ),
    ]
