# Generated by Django 2.0.2 on 2018-02-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180226_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('EUR USD', 'EUR USD'), ('Bitcoin', 'Bitcoin')], help_text='Наименование валюты', max_length=16),
        ),
    ]
