# Generated by Django 2.0.2 on 2018-02-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180226_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('Валюты', (('EUR USD', 'EUR USD'),)), ('Биржевые акции', ()), ('Криптоактивы', (('Bitcoin', 'Bitcoin'),)), ('Индексы', ()), ('Сырье', ())], help_text='Наименование валюты', max_length=16),
        ),
    ]
