# Generated by Django 2.0.2 on 2018-02-26 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(help_text='Наименование валюты', max_length=16, null=True)),
                ('value', models.DecimalField(decimal_places=10, default=0.0, help_text='Предсказанное значение', max_digits=20, null=True)),
                ('time', models.DateTimeField(help_text='Дата и время')),
                ('is_call', models.NullBooleanField(help_text='Будет ли повышение')),
                ('chahce', models.FloatField(blank=True, help_text='Вероятность', null=True)),
                ('from_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время предсказания')),
            ],
        ),
    ]
